Console.Write("Введите первое число:");
int n = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите второе число:");
int m = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите третье число:");
int l = Convert.ToInt32(Console.ReadLine());
int max = n;
if (m > max) max = m;
if (l > max) max = l;
Console.Write("max=");
Console.Write(max);